### ISSUE TITLE
Social media: Add an endpoint to remove posts from queue.

### ISSUE THREAD

**Issue by storymode7** [CuriousLearner/nexus#21]
There should be a way to remove posts from nexus' queue other than admin interface.

**Comment by GeekyShacklebolt** [comment]
I have submitted this [PR](https://github.com/CuriousLearner/nexus/pull/22), to implement a new endpoint to unapprove a post via `POST /api/posts/:post_id/unapprove`. So that a `core_organizer` can unapprove a post that has been approved but not published yet.

That means, before the execution of the next celery beat task, now it is possible to stop a post from getting queued.

**Comment by storymode7** [comment]
Fixed in https://github.com/CuriousLearner/nexus/pull/22
